# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messaging.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'messaging.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmessaging.proto\"%\n\x0e\x43onnectRequest\x12\x13\n\x0bsender_name\x18\x01 \x01(\t\"E\n\x12SendMessageRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x11\n\trecipient\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\"\'\n\x07Message\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2f\n\x10MessagingService\x12&\n\x07\x43onnect\x12\x0f.ConnectRequest\x1a\x08.Message0\x01\x12*\n\x0bSendMessage\x12\x13.SendMessageRequest\x1a\x06.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messaging_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONNECTREQUEST']._serialized_start=19
  _globals['_CONNECTREQUEST']._serialized_end=56
  _globals['_SENDMESSAGEREQUEST']._serialized_start=58
  _globals['_SENDMESSAGEREQUEST']._serialized_end=127
  _globals['_MESSAGE']._serialized_start=129
  _globals['_MESSAGE']._serialized_end=168
  _globals['_EMPTY']._serialized_start=170
  _globals['_EMPTY']._serialized_end=177
  _globals['_MESSAGINGSERVICE']._serialized_start=179
  _globals['_MESSAGINGSERVICE']._serialized_end=281
# @@protoc_insertion_point(module_scope)
